// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: 689eeffa530e83364d79e142c0928c67156557845c8d6f32b5950ce3b4dcadf6

// noinspection JSUnusedGlobalSymbols

export type ThemeName = "colormatic-keycloak-theme";

export const themeNames: ThemeName[] = ["colormatic-keycloak-theme"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext =
	| import("./login/KcContext").KcContext
	| import("./account/KcContext").KcContext;

declare global {
	interface Window {
		kcContext?: KcContext;
	}
}
